/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { forwardRef, useEffect, useRef, useState } from "react";
import {
  Box,
  Sphere,
  Trail,
  useAnimations,
  useGLTF,
  useKeyboardControls,
} from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { RapierCollider, RapierRigidBody } from "@react-three/rapier";
import { useGameStore } from "../../stores/gameStore";
import { useGame, useJoystickControls } from "ecctrl";
import { useEnemyStore } from "../../stores/enemyStore";
import { useFrame } from "@react-three/fiber";
import { useSound } from "../../hooks/useSound";

type GLTFResult = GLTF & {
  nodes: {
    model_T: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    ["Body.003"]: THREE.MeshPhysicalMaterial;
  };
};

export const Hero = forwardRef<RapierRigidBody>(function (
  props: JSX.IntrinsicElements["group"],
  ref
) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/player.glb") as GLTFResult;
  const gameStore = useGameStore();
  const joystick = useJoystickControls();

  const [attack, setAttack] = useState(false);
  const { currentEnemy } = useGameStore();
  const { enemies } = useEnemyStore();
  const { playSound } = useSound();

  useEffect(() => {
    setAttack(joystick.curButton5Pressed);
  }, [joystick.curButton5Pressed]);

  const [sub] = useKeyboardControls();

  useEffect(() => {
    return sub(
      (state) => state.action1,
      (pressed) => {
        setAttack(pressed);
      }
    );
  }, []);

  useEffect(() => {
    if (!attack) return;
    playSound("attack");
    // Make sure ref exists and has a current property
    if (ref && typeof ref === "object" && "current" in ref && ref.current) {
      // Make sure enemy exists before accessing its position
      const playerPos = ref.current.translation();
      const enemy = enemies.find((enemy) => enemy.id === currentEnemy);
      const enemyPos = enemy?.position ?? new THREE.Vector3(0, 0, 0);
      // Create a proper Vector3 for the target position
      const targetPos = new THREE.Vector3(enemyPos.x, enemyPos.y, enemyPos.z);

      window.pos = playerPos;
      // Set the attack with proper positio dns
      gameStore.setAttack({
        initial: new THREE.Vector3(playerPos.x, playerPos.y + 1, playerPos.z),
        target: targetPos,
      });
    }
  }, [attack]);

  return (
    <group ref={group} {...props} position={[0, -0.9, 0]} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[0.471, 0, 0]}>
          <skinnedMesh
            name="model_T"
            geometry={nodes.model_T.geometry}
            material={materials["Body.003"]}
            skeleton={nodes.model_T.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/player.glb");
