import { Item } from "../types";

export const items: Item[] = [
  {
    id: "sword",
    name: "Steel Sword",
    emoji: "⚔️",
    description: "A sharp blade",
    value: 100,
    type: "weapon",
  },
  {
    id: "bow",
    name: "Wooden Bow",
    emoji: "🏹",
    description: "For ranged attacks",
    value: 80,
    type: "weapon",
  },
  {
    id: "staff",
    name: "Magic Staff",
    emoji: "🪄",
    description: "Channels magical power",
    value: 120,
    type: "weapon",
  },
  {
    id: "shield",
    name: "Iron Shield",
    emoji: "🛡️",
    description: "Solid protection",
    value: 90,
    type: "armor",
  },
  {
    id: "helmet",
    name: "Knight Helmet",
    emoji: "⛑️",
    description: "Head protection",
    value: 70,
    type: "armor",
  },
  {
    id: "chestplate",
    name: "Steel Armor",
    emoji: "🥋",
    description: "Body protection",
    value: 150,
    type: "armor",
  },
  {
    id: "boots",
    name: "Leather Boots",
    emoji: "👢",
    description: "Fast movement",
    value: 50,
    type: "armor",
  },
  {
    id: "health_potion",
    name: "Health Potion",
    emoji: "❤️",
    description: "Restores health",
    value: 30,
    type: "potion",
  },
  {
    id: "mana_potion",
    name: "Mana Potion",
    emoji: "🌟",
    description: "Restores mana",
    value: 30,
    type: "potion",
  },
  {
    id: "strength_potion",
    name: "Strength Potion",
    emoji: "💪",
    description: "Increases strength",
    value: 40,
    type: "potion",
  },
  {
    id: "wood",
    name: "Wood",
    emoji: "🪵",
    description: "Building material",
    value: 10,
    type: "material",
  },
  {
    id: "stone",
    name: "Stone",
    emoji: "🪨",
    description: "Building material",
    value: 15,
    type: "material",
  },
  {
    id: "iron_ore",
    name: "Iron Ore",
    emoji: "⛰️",
    description: "Metal resource",
    value: 25,
    type: "material",
  },
  {
    id: "gold_ore",
    name: "Gold Ore",
    emoji: "💎",
    description: "Precious metal",
    value: 50,
    type: "material",
  },
  {
    id: "ancient_scroll",
    name: "Ancient Scroll",
    emoji: "📜",
    description: "Contains secrets",
    value: 200,
    type: "quest",
  },
  {
    id: "magic_crystal",
    name: "Magic Crystal",
    emoji: "🔮",
    description: "Magical power source",
    value: 150,
    type: "quest",
  },
  {
    id: "dragon_scale",
    name: "Dragon Scale",
    emoji: "🐉",
    description: "Rare material",
    value: 300,
    type: "quest",
  },
  {
    id: "bread",
    name: "Fresh Bread",
    emoji: "🍞",
    description: "Restores energy",
    value: 15,
    type: "food",
  },
  {
    id: "apple",
    name: "Apple",
    emoji: "🍎",
    description: "Healthy food",
    value: 10,
    type: "food",
  },
  {
    id: "meat",
    name: "Cooked Meat",
    emoji: "🍖",
    description: "Protein rich",
    value: 25,
    type: "food",
  },
  {
    id: "fire_potion",
    name: "Fire Potion",
    emoji: "🔥",
    description: "Sets enemies ablaze",
    value: 60,
    type: "potion",
  },
  {
    id: "ice_potion",
    name: "Ice Potion",
    emoji: "❄️",
    description: "Freezes enemies",
    value: 60,
    type: "potion",
  },
  {
    id: "axe",
    name: "Battle Axe",
    emoji: "🪓",
    description: "Heavy but powerful",
    value: 110,
    type: "weapon",
  },
  {
    id: "dagger",
    name: "Poisoned Dagger",
    emoji: "🗡️",
    description: "Fast but deadly",
    value: 90,
    type: "weapon",
  },
  {
    id: "magic_book",
    name: "Book of Spells",
    emoji: "📖",
    description: "Contains ancient spells",
    value: 200,
    type: "quest",
  },
  {
    id: "silver_coin",
    name: "Silver Coin",
    emoji: "🪙",
    description: "Currency for trade",
    value: 5,
    type: "material",
  },
  {
    id: "gold_coin",
    name: "Gold Coin",
    emoji: "🪙",
    description: "Valuable currency",
    value: 10,
    type: "material",
  },
  {
    id: "fish",
    name: "Grilled Fish",
    emoji: "🐟",
    description: "Tasty and nutritious",
    value: 20,
    type: "food",
  },
  {
    id: "cheese",
    name: "Wheel of Cheese",
    emoji: "🧀",
    description: "Rich and delicious",
    value: 25,
    type: "food",
  },
  {
    id: "torch",
    name: "Torch",
    emoji: "🔥",
    description: "Lights up dark places",
    value: 15,
    type: "material",
  },
  {
    id: "rope",
    name: "Strong Rope",
    emoji: "🪢",
    description: "Useful for climbing",
    value: 20,
    type: "material",
  },
  {
    id: "pear",
    name: "Pear",
    emoji: "🍐",
    description: "Juicy fruit",
    value: 10,
    type: "food",
  },
  {
    id: "carrot",
    name: "Carrot",
    emoji: "🥕",
    description: "Crunchy vegetable",
    value: 10,
    type: "food",
  },
  {
    id: "water_bottle",
    name: "Water Bottle",
    emoji: "💧",
    description: "Quenches thirst",
    value: 5,
    type: "food",
  },
  {
    id: "ring_of_power",
    name: "Ring of Power",
    emoji: "💍",
    description: "Boosts abilities",
    value: 300,
    type: "quest",
  },
  {
    id: "enchanted_boots",
    name: "Enchanted Boots",
    emoji: "🥾",
    description: "Boosts speed",
    value: 200,
    type: "armor",
  },
  {
    id: "mystic_robe",
    name: "Mystic Robe",
    emoji: "🥋",
    description: "Enhances magic",
    value: 250,
    type: "armor",
  },
  {
    id: "mead",
    name: "Bottle of Mead",
    emoji: "🍺",
    description: "Restores energy",
    value: 15,
    type: "food",
  },
  {
    id: "grapes",
    name: "Grapes",
    emoji: "🍇",
    description: "Sweet and juicy",
    value: 15,
    type: "food",
  },
  {
    id: "magic_wand",
    name: "Magic Wand",
    emoji: "🪄",
    description: "Casts powerful spells",
    value: 180,
    type: "weapon",
  },
  {
    id: "pickaxe",
    name: "Pickaxe",
    emoji: "⛏️",
    description: "Useful for mining",
    value: 50,
    type: "material",
  },
  {
    id: "treasure_chest",
    name: "Treasure Chest",
    emoji: "🪙",
    description: "Contains loot",
    value: 500,
    type: "quest",
  },
  {
    id: "emerald_gem",
    name: "Emerald Gem",
    emoji: "💚",
    description: "Rare and valuable",
    value: 350,
    type: "quest",
  },
  {
    id: "phoenix_feather",
    name: "Phoenix Feather",
    emoji: "🪶",
    description: "Legendary item",
    value: 500,
    type: "quest",
  },
  {
    id: "silver_ring",
    name: "Silver Ring",
    emoji: "💍",
    description: "Simple but elegant",
    value: 50,
    type: "armor",
  },
  {
    id: "platinum_coin",
    name: "Platinum Coin",
    emoji: "🪙",
    description: "Extremely valuable currency",
    value: 100,
    type: "material",
  },
  {
    id: "fire_rod",
    name: "Fire Rod",
    emoji: "🔥",
    description: "Casts fire spells",
    value: 200,
    type: "weapon",
  },
  {
    id: "ice_shield",
    name: "Ice Shield",
    emoji: "❄️",
    description: "Protects against fire attacks",
    value: 150,
    type: "armor",
  },
  {
    id: "lightning_sword",
    name: "Lightning Sword",
    emoji: "⚡",
    description: "Electrifies enemies",
    value: 250,
    type: "weapon",
  },
  {
    id: "magic_ring",
    name: "Magic Ring",
    emoji: "💍",
    description: "Enhances magical abilities",
    value: 180,
    type: "armor",
  },
  {
    id: "ruby",
    name: "Ruby",
    emoji: "🔴",
    description: "A precious red gem",
    value: 300,
    type: "material",
  },
  {
    id: "sapphire",
    name: "Sapphire",
    emoji: "🔵",
    description: "A precious blue gem",
    value: 300,
    type: "material",
  },
  {
    id: "emerald",
    name: "Emerald",
    emoji: "💚",
    description: "A precious green gem",
    value: 300,
    type: "material",
  },
  {
    id: "diamond",
    name: "Diamond",
    emoji: "💎",
    description: "The most precious gem",
    value: 500,
    type: "material",
  },
  {
    id: "venom_dagger",
    name: "Venom Dagger",
    emoji: "🗡️",
    description: "Poisons enemies",
    value: 120,
    type: "weapon",
  },
  {
    id: "shadow_cloak",
    name: "Shadow Cloak",
    emoji: "🕶️",
    description: "Grants invisibility",
    value: 300,
    type: "armor",
  },
  {
    id: "dragon_helm",
    name: "Dragon Helm",
    emoji: "🐉",
    description: "Grants dragon-like powers",
    value: 400,
    type: "armor",
  },
  {
    id: "golden_apple",
    name: "Golden Apple",
    emoji: "🍎",
    description: "Restores a lot of health",
    value: 100,
    type: "food",
  },
  {
    id: "health_elixir",
    name: "Health Elixir",
    emoji: "❤️",
    description: "Fully restores health",
    value: 150,
    type: "potion",
  },
  {
    id: "mana_elixir",
    name: "Mana Elixir",
    emoji: "🌟",
    description: "Fully restores mana",
    value: 150,
    type: "potion",
  },
  {
    id: "fire_crystal",
    name: "Fire Crystal",
    emoji: "🔥",
    description: "Source of fire magic",
    value: 200,
    type: "quest",
  },
  {
    id: "ice_crystal",
    name: "Ice Crystal",
    emoji: "❄️",
    description: "Source of ice magic",
    value: 200,
    type: "quest",
  },
  {
    id: "storm_crystal",
    name: "Storm Crystal",
    emoji: "⚡",
    description: "Source of lightning magic",
    value: 200,
    type: "quest",
  },
  {
    id: "phoenix_down",
    name: "Phoenix Down",
    emoji: "🪶",
    description: "Revives a fallen ally",
    value: 300,
    type: "quest",
  },
  {
    id: "mystic_orb",
    name: "Mystic Orb",
    emoji: "🔮",
    description: "Holds untold power",
    value: 350,
    type: "quest",
  },
  {
    id: "dragon_bone",
    name: "Dragon Bone",
    emoji: "🐉",
    description: "A rare crafting material",
    value: 400,
    type: "material",
  },
  {
    id: "wolf_meat",
    name: "Wolf Meat",
    emoji: "🍖",
    description: "Restores energy",
    value: 20,
    type: "food",
  },
  {
    id: "cooked_rice",
    name: "Cooked Rice",
    emoji: "🍚",
    description: "Staple food",
    value: 15,
    type: "food",
  },
  {
    id: "honey",
    name: "Jar of Honey",
    emoji: "🍯",
    description: "Sweet and energizing",
    value: 25,
    type: "food",
  },
  {
    id: "potion_bag",
    name: "Potion Bag",
    emoji: "🎒",
    description: "Holds multiple potions",
    value: 200,
    type: "material",
  },
  {
    id: "steel_hammer",
    name: "Steel Hammer",
    emoji: "🔨",
    description: "Useful for crafting",
    value: 100,
    type: "weapon",
  },
  {
    id: "dark_mirror",
    name: "Dark Mirror",
    emoji: "🪞",
    description: "Reveals hidden truths",
    value: 400,
    type: "quest",
  },
  {
    id: "fairy_dust",
    name: "Fairy Dust",
    emoji: "✨",
    description: "Used in magic crafting",
    value: 100,
    type: "material",
  },
  {
    id: "ancient_key",
    name: "Ancient Key",
    emoji: "🗝️",
    description: "Opens old doors",
    value: 200,
    type: "quest",
  },
  {
    id: "book_of_heroes",
    name: "Book of Heroes",
    emoji: "📚",
    description: "Details ancient heroes",
    value: 500,
    type: "quest",
  },
  {
    id: "guardian_helm",
    name: "Guardian Helm",
    emoji: "🪖",
    description: "Worn by legendary warriors",
    value: 350,
    type: "armor",
  },
  {
    id: "hunter_bow",
    name: "Hunter Bow",
    emoji: "🏹",
    description: "Perfect for long-range attacks",
    value: 150,
    type: "weapon",
  },
  {
    id: "iron_boots",
    name: "Iron Boots",
    emoji: "🥾",
    description: "Strong but heavy",
    value: 120,
    type: "armor",
  },
  {
    id: "healing_herb",
    name: "Healing Herb",
    emoji: "🌿",
    description: "Restores health over time",
    value: 20,
    type: "potion",
  },
  {
    id: "poison_herb",
    name: "Poison Herb",
    emoji: "🍃",
    description: "Can be used to craft poison",
    value: 30,
    type: "material",
  },
  {
    id: "dragon_fruit",
    name: "Dragon Fruit",
    emoji: "🍍",
    description: "Exotic and energizing",
    value: 50,
    type: "food",
  },
  {
    id: "battle_horn",
    name: "Battle Horn",
    emoji: "📯",
    description: "Used to call allies",
    value: 200,
    type: "quest",
  },
  {
    id: "guardian_sword",
    name: "Guardian Sword",
    emoji: "🗡️",
    description: "Forged for the chosen",
    value: 400,
    type: "weapon",
  },
  {
    id: "iron_plating",
    name: "Iron Plating",
    emoji: "🛡️",
    description: "Heavy-duty protection",
    value: 300,
    type: "armor",
  },
  {
    id: "goblin_meat",
    name: "Goblin Meat",
    emoji: "🍖",
    description: "Not very appetizing",
    value: 10,
    type: "food",
  },
  {
    id: "ancient_statue",
    name: "Ancient Statue",
    emoji: "🗿",
    description: "Depicts a long-lost hero",
    value: 500,
    type: "quest",
  },
  {
    id: "mystic_ring",
    name: "Mystic Ring",
    emoji: "💍",
    description: "Boosts magic powers",
    value: 300,
    type: "armor",
  },
];
